version: '2'

services:
  ethereum-compiler:
    build:
      context: .
      dockerfile: ./docker/ethereum-voting.Dockerfile
    volumes:
      - ./:/opt/election/
    #command: make deploy-contract

  voting-api:
    build:
      context: .
      dockerfile: ./docker/ethereum-voting.Dockerfile
    volumes:
      - ./:/opt/election/
    environment:
      - FLASK_APP=/opt/election/flask/app.py
    ports:
      - 5000:5000
    command: flask run --host=0.0.0.0

  geth-client:
    build:
      context: .
      dockerfile: ./docker/geth-client.Dockerfile
    env_file:
      - ./docker/passwords.env
    volumes:
      - ./config:/etc/blockchain_config
    ports:
      - 3000:3000
      - 8545:8545
    entrypoint: sh -c
