version: '2'

services:
  ethereum-compiler:
    build:
      context: .
      dockerfile: ./docker/ethereum-voting.Dockerfile
    volumes:
      - ./:/opt/election/
    #command: make deploy-contract

  voting-api:
    build:
      context: .
      dockerfile: ./docker/ethereum-voting.Dockerfile
    volumes:
      - ./:/opt/election/
    environment:
      - FLASK_APP=/opt/election/flask/app.py
    ports:
      - 5000:5000
    command: flask run --host=0.0.0.0

  geth-client:
    build:
      context: .
      dockerfile: ./docker/geth-client.Dockerfile
    env_file:
      - ./docker/passwords.env
    volumes:
      - ./config:/etc/blockchain_config
      - ./config/datadir:/root/.ethereum/
    ports:
      - 3000:3000
      - 8545:8545
      - 30303:30303
    entrypoint: sh -c
    command: geth --port "3000" --nodiscover --datadir=/etc/blockchain_config/datadir  --rpc --rpcport "8545" --maxpeers=25 --rpcaddr 0.0.0.0 --rpccorsdomain "*" --ipcapi --rpcapi "personal,admin,db,eth,net,web3,miner,shh,txpool,debug" --nat "any" 
